server:
  port: 9191
  
spring:
  application:
    name: api-gateway   
  cloud:
    gateway:
      mvc:       
        routes:
        - id: department
          uri: lb://department
          predicates:
           -  Path=/departments/**
        - id: user
          uri: lb://user
          predicates:
          - Path=/users/**
             
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
     defaultZone: http://localhost:8761/eureka/
    
  instance:
    hostname: localhost
