server:
  port: 9296
  
spring:
 application:
  name: config-service
  
 cloud:
    config:
      server:
       git: 
        uri: https://github.com/ak79494/ms/
        default-label: main
        clone-on-start: true
      
